# Generated by Django 4.2.6 on 2023-11-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spouse',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
