# Generated by Django 4.2.6 on 2023-12-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_confrimation_date_spouse_confirmation_date'),
    ]

    operations = [
    ]
