# Generated by Django 4.2.6 on 2024-01-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20231209_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('dept', models.CharField(blank=True, choices=[('sunday sch.', 'Sunday Sch'), ('teens', 'Teens')], max_length=11, null=True)),
                ('member_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.memberprofile')),
            ],
        ),
    ]
