# Generated by Django 4.2.6 on 2024-01-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spouse',
            name='name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
    ]
