# Generated by Django 4.2.6 on 2024-01-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_children_name_alter_spouse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('kama', 'Kama'), ('MoU', 'MOU'), ('choir', 'Choir'), ('kayo', 'Kayo')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='spouse',
            name='department',
            field=models.CharField(blank=True, choices=[('kama', 'Kama'), ('MoU', 'MOU'), ('choir', 'Choir'), ('kayo', 'Kayo')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='spouse',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
    ]
