# Generated by Django 4.2.6 on 2024-01-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_children_gender_memberprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='dept',
            field=models.CharField(blank=True, choices=[('sunday_sch', 'Sunday Sch'), ('teens', 'Teens')], max_length=11, null=True),
        ),
    ]
