# Generated by Django 5.0.3 on 2024-03-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spouse',
            name='department',
            field=models.CharField(blank=True, choices=[('MoU', 'MoU'), ('Choir', 'Choir')], max_length=6, null=True),
        ),
    ]
